// Generated by CoffeeScript 1.9.0
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['$'], factory);
  } else if (typeof module !== 'undefined' && module.exports) {
    module.exports = factory(require('jquery'));
  } else {
    root.ModuleName || (root.ModuleName = factory(root.jQuery));
  }
})(this, function() {
  "use strict";
  var Rollover;
  Rollover = (function() {
    Rollover.prototype._defaults = {
      offStr: '_off',
      onStr: '_on',
      childOnly: true
    };

    Rollover.prototype._prepareSrcs = function() {
      this._srcOff = this.$img.attr('src');
      return this._srcOn = this._srcOff.replace(this.opts.offStr, this.opts.onStr);
    };

    Rollover.prototype._preload = function() {
      return $('<img />').attr('src', this._srcOn);
    };

    function Rollover(_at_el, opts) {
      this.el = _at_el;
      this.opts = $.extend({}, this._defaults, opts);
      this.$el = $(this.el);
      if (this.opts.childOnly) {
        this.$img = this.$el.children('img');
      } else {
        this.$img = $el.find('img');
      }
      this._prepareSrcs();
      this._preload();
      this.addEvents();
    }

    Rollover.prototype.toOver = function() {
      this.$img.attr('src', this._srcOn);
      return this;
    };

    Rollover.prototype.toNormal = function() {
      this.$img.attr('src', this._srcOff);
      return this;
    };

    Rollover.prototype.addEvents = function() {
      this.$el.on('mouseenter.rollover', (function(_this) {
        return function() {
          return _this.toOver();
        };
      })(this));
      this.$el.on('mouseleave.rollover', (function(_this) {
        return function() {
          return _this.toNormal();
        };
      })(this));
      return this;
    };

    Rollover.prototype.rmEvents = function() {
      this.$el.off('mouseenter.rollover');
      this.$el.off('mouseleave.rollover');
      return this;
    };

    Rollover.prototype.destroy = function() {
      return this.$el.remove();
    };

    return Rollover;

  })();
});
